import streamlit as st
import pandas as pd
import os
import base64
from datetime import datetime
from streamlit_js_eval import streamlit_js_eval 

st.set_page_config(page_title="FORM NA ALI UMAR", page_icon="🖥️", layout="wide")

FILE_NAME = "MASU_AURE.CSV"
ADMIN_PASSWORD = "ALI@123" 

# ====== KARANTAR WALFA ======
@st.cache_data
def GET_IMG_AS_BASE64(FILE):
    TRY:
        WITH OPEN(FILE, "RB") AS F:
            DATA = F.READ()
        RETURN BASE64.B64ENCODE(DATA).DECODE()
    EXCEPT:
        RETURN ""

BG = GET_IMG_AS_BASE64("LOGO.JPG") # <-- NA CANZA ZUWA LOGO.JPG KAMAR YADDA KAKE DA SHI

# ====== CSS MAI RUBUTU MAI JA MAI GIRMA ======
ST.MARKDOWN(F"""
    <STYLE>
    @IMPORT URL('HTTPS://FONTS.GOOGLEAPIS.COM/CSS2?FAMILY=POPPINS:WGHT@400;600;700;800;900&DIPLAY=SWAP');
    HTML, BODY, [CLASS*="CSS"] {{FONT-FAMILY: 'POPPINS', SANS-SERIF;}}
    
    /* 1. WALFA TA WEBSITE */
    .STAPP {{
        BACKGROUND-IMAGE: URL("DATA:IMAGE/JPEG;BASE64,{BG}");
        BACKGROUND-SIZE: COVER;
        BACKGROUND-POSITION: CENTER;
        BACKGROUND-ATTACHMENT: FIXED;
    }}
    
    /* 2. KATIN BAKI MAI DUHU SOSAI DON JA YA FITO */
    .MAIN-CONTAINER {{
        MAX-WIDTH: 900PX; 
        MARGIN: 40PX AUTO; 
        BACKGROUND: RGBA(0, 0, 0, 0.8); /* BAKI MAI DUHU 80% */
        BORDER-RADIUS: 30PX; 
        PADDING: 3.5REM; 
        BOX-SHADOW: 0 25PX 60PX RGBA(255,0,0,0.4); 
        BORDER: 5PX SOLID #FF0000; /* JA BORDER */
    }}
    
    /* 3. TITLE MAI JA MAI GIRMA */
    .TITLE {{
        TEXT-ALIGN: CENTER; 
        COLOR: #FF0000; /* JA */
        FONT-SIZE: 55PX; /* MAI GIRMA SOSAI */
        FONT-WEIGHT: 900; 
        MARGIN-BOTTOM: 20PX;
        TEXT-TRANSFORM: UPPERCASE;
        TEXT-SHADOW: 3PX 3PX 6PX BLACK; /* INUWA DON YA FITO */
        LETTER-SPACING: 3PX;
    }}
    
    /* 4. WELCOME MAI JA MAI KATO SOSAI */
    .WELCOME {{
        TEXT-ALIGN: CENTER; 
        COLOR: #FF0000; /* JA */
        FONT-SIZE: 26PX; /* NA KARA GIRMA SOSAI */
        MARGIN-BOTTOM: 40PX;
        FONT-WEIGHT: 900; /* BOLD SOSAI */
        LINE-HEIGHT: 2.2; /* SARARI MAI YAWA */
        WHITE-SPACE: PRE-LINE; 
        TEXT-TRANSFORM: UPPERCASE;
        TEXT-SHADOW: 2PX 2PX 4PX BLACK; /* INUWA DON YA FITO AKAN WALFA */
        LETTER-SPACING: 1PX;
    }}
    
    /* 5. INPUTS DA LABELS MAI JA */
    LABEL {{COLOR: #FF0000 !IMPORTANT; FONT-WEIGHT: 900 !IMPORTANT; FONT-SIZE: 24PX !IMPORTANT; TEXT-TRANSFORM: UPPERCASE; TEXT-SHADOW: 1PX 1PX 2PX BLACK;}}
    
    .STTEXTINPUT>DIV>DIV>INPUT, .STNUMBERINPUT>DIV>DIV>INPUT {{
        BORDER-RADIUS: 15PX; 
        BORDER: 5PX SOLID #FF0000;
        BACKGROUND: RGBA(255,255,255,0.95);
        COLOR: BLACK;
        FONT-WEIGHT: 900;
        FONT-SIZE: 24PX; 
        PADDING: 18PX;
        HEIGHT: 3.8EM;
        TEXT-TRANSFORM: CAPITALIZE;
    }}
    
    .STRADIO > DIV {{BACKGROUND: RGBA(255,255,255,0.95); PADDING: 22PX; BORDER-RADIUS: 15PX; BORDER: 4PX SOLID #FF0000;}}
    .STRADIO LABEL {{FONT-SIZE: 22PX !IMPORTANT; FONT-WEIGHT: 900 !IMPORTANT; TEXT-TRANSFORM: UPPERCASE; COLOR: #0D47A1 !IMPORTANT;}}
    
    /* 6. BUTTON MAI JA MAI KATO */
    .STBUTTON>BUTTON {{
        BACKGROUND: LINEAR-GRADIENT(90DEG, #FF0000 0%, #8B0000 100%); /* JA ZUWA DUHUN JA */
        COLOR: WHITE; 
        BORDER-RADIUS: 20PX; 
        HEIGHT: 4.8EM; 
        WIDTH: 100%; 
        FONT-SIZE: 32PX; /* MAI GIRMA SOSAI */
        FONT-WEIGHT: 900; 
        BORDER: NONE;
        MARGIN-TOP: 30PX;
        LETTER-SPACING: 3PX;
        TEXT-TRANSFORM: UPPERCASE;
        BOX-SHADOW: 0 8PX 20PX RGBA(255,0,0,0.5);
    }}
    .STBUTTON>BUTTON:HOVER {{TRANSFORM: SCALE(1.08); TRANSITION: 0.3S;}}
    
    .STALERT {{FONT-SIZE: 22PX !IMPORTANT; FONT-WEIGHT: 900 !IMPORTANT; TEXT-TRANSFORM: UPPERCASE;}}
    
    @MEDIA (MAX-WIDTH: 900PX) {{
        .MAIN-CONTAINER {{PADDING: 2REM; MARGIN: 15PX;}}
        .TITLE {{FONT-SIZE: 38PX;}}
        .WELCOME {{FONT-SIZE: 20PX;}}
    }}
    </STYLE>
""", UNSAFE_ALLOW_HTML=TRUE)

DEF SAVE_USER(SUNA, JINSI, SHEKARU, LOKACI, DEVICE_INFO):
    IF NOT OS.PATH.EXISTS(FILE_NAME):
        DF = PD.DATAFRAME(COLUMNS=["SUNA", "JINSI", "SHEKARU", "LOKACIN REGISTER", "DEVICE/BROWSER"])
    ELSE:
        DF = PD.READ_CSV(FILE_NAME)
    NEW_DATA = PD.DATAFRAME([[SUNA, JINSI, SHEKARU, LOKACI, DEVICE_INFO]], COLUMNS=["SUNA", "JINSI", "SHEKARU", "LOKACIN REGISTER", "DEVICE/BROWSER"])
    DF = PD.CONCAT([DF, NEW_DATA], IGNORE_INDEX=TRUE)
    DF.TO_CSV(FILE_NAME, INDEX=FALSE)

DEF LOAD_USERS():
    IF OS.PATH.EXISTS(FILE_NAME):
        RETURN PD.READ_CSV(FILE_NAME)
    ELSE:
        RETURN PD.DATAFRAME(COLUMNS=["SUNA", "JINSI", "SHEKARU", "LOKACIN REGISTER", "DEVICE/BROWSER"])

DEVICE_INFO = STREAMLIT_JS_EVAL(JS_EXPRESSIONS='NAVIGATOR.USERAGENT', KEY='UA')
MENU = ST.SIDEBAR.RADIO("📋 MENU", ["FORM NA REGISTER", "SHAFIN ADMIN 🔒"])

IF MENU == "FORM NA REGISTER":
    ST.MARKDOWN('<DIV CLASS="MAIN-CONTAINER">', UNSAFE_ALLOW_HTML=TRUE)
        
    ST.MARKDOWN('<P CLASS="TITLE">🖥️ FORM NA ALI UMAR</P>', UNSAFE_ALLOW_HTML=TRUE)
    
    WELCOME_TEXT = """INA MAIYI MUKU BARKA DA ZIYARTAR SHAFINA SUNANA ALI UMAR MUHAMMAD NI DALIBIN CYBER SECURITY NE WANNAN WEBSITE DIN NA KIR KIRESHINE DOMIN TEST DAKUMA GWAJE GWAJE NA HARKAR PYTHON PROGRAMMING 

ZAKU IYA CIKA SUNANKU DA SHEKARUNKU WANNAN WEBSITE DIN INDAI KAFADA MASA 
SHEKARUNKA DAIDAI ZAIFADA MAKA KA KAI KAYI AURE NE KO BAKA KAIBA🙄

🤣😄😂 WANNAN SHINE LOKACIN FARKO DANA FARA KIR KIRAN ABU 

🖥️🖥️🖥️🙏 INA MAI YIMUKU GODIYA DA ZIYARTAR SHAFINA🫣

🙏NAGODE"""
    
    ST.MARKDOWN(F'<P CLASS="WELCOME">{WELCOME_TEXT}</P>', UNSAFE_ALLOW_HTML=TRUE)

    WITH ST.FORM("REGISTER_FORM", CLEAR_ON_SUBMIT=TRUE):
        SUNA = ST.TEXT_INPUT("1. MEYE SUNANKA?")
        SHEKARU = ST.NUMBER_INPUT("2. SHEKARUNKA NAWA?", MIN_VALUE=1, MAX_VALUE=100, STEP=1)
        JINSI = ST.RADIO("3. KAI NAMIJI NE KO MACE?", ["NAMIJI", "MACE"], HORIZONTAL=TRUE)
        SUBMITTED = ST.FORM_SUBMIT_BUTTON("AIKA FORM 🚀")

        IF SUBMITTED:
            IF SUNA AND SHEKARU:
                LOKACI = DATETIME.NOW().STRFTIME("%Y-%M-%D %H:%M:%S")
                SAVE_USER(SUNA, JINSI, SHEKARU, LOKACI, DEVICE_INFO)
                ST.SUCCESS(F"BARKA DA ZUWA {SUNA}!", ICON="✅")
                IF SHEKARU >= 18: ST.INFO(F"AN KARBE KA! KA GIRMA KAKAI AURE ✅")
                ELSE: ST.WARNING(F"BAKA KAI AUREBA. KAJIRA SHEKARA {18 - SHEKARU} TUKUNNAN ❌")
                IF SHEKARU >= 35: ST.ERROR("KAI KA WUCE AURE. KA YI GIRMA SOSAI 😂")
                ST.BALLOONS()
            ELSE: ST.ERROR("TAF, DA FATAN KA CIKA DUKKAN BAYANAI")
    
    ST.MARKDOWN('</DIV>', UNSAFE_ALLOW_HTML=TRUE)

ELIF MENU == "SHAFIN ADMIN 🔒":
    ST.MARKDOWN('<DIV CLASS="MAIN-CONTAINER">', UNSAFE_ALLOW_HTML=TRUE)
    ST.MARKDOWN('<P CLASS="TITLE">🔐 SHAFIN ADMIN</P>', UNSAFE_ALLOW_HTML=TRUE)
    PASSWORD = ST.TEXT_INPUT("SHIGAR DA PASSWORD NA ADMIN", TYPE="PASSWORD")
    IF PASSWORD == ADMIN_PASSWORD:
        DF = LOAD_USERS()
        IF NOT DF.EMPTY:
            ST.SUCCESS("BARKA DA ZUWA ADMIN!", ICON="👑")
            COL1, COL2, COL3 = ST.COLUMNS(3)
            WITH COL1: ST.METRIC("JIMILLA", LEN(DF))
            WITH COL2: ST.METRIC("MAZAJE", LEN(DF[DF["JINSI"] == "NAMIJI"]))
            WITH COL3: ST.METRIC("MATA", LEN(DF[DF["JINSI"] == "MACE"]))
            ST.DATAFRAME(DF, USE_CONTAINER_WIDTH=TRUE)
            ST.DOWNLOAD_BUTTON("📥 SAUKE DATA", DF.TO_CSV(INDEX=FALSE).ENCODE('UTF-8'), "MASU_AURE.CSV", "TEXT/CSV")
        ELSE: ST.INFO("BABU WANDA YA YI REGISTER TUKUNA")
    ELIF PASSWORD: ST.ERROR("PASSWORD BA DAIDAI BA NE ❌")
    ST.MARKDOWN('</DIV>', UNSAFE_ALLOW_HTML=TRUE)
